Add vrrp virtual address
IETF-OPSAWG-WG/lxnm pull request #289
Opened 2021-04-28 12:34 UTC by sbarguil

Virtual IPv4 addresses for a single VRRP group.

2021-05-03 08:44 UTC, boucadair requested changes

2021-05-03 08:44 UTC, boucadair commented on yang/ietf-l3vpn-ntw.yang
> +                      leaf virtual-ip-address {
To be defined as a leaf-list

Note that this is defined as list virtual-ipv4-address and list virtual-ipv6-address in rfc8347, but I think that a leaf-list is more approrpiate.

2021-05-03 08:44 UTC, boucadair commented on yang/ietf-l3vpn-ntw.yang
> +                        reference
No need to have an IPv4-specific reference as the type is inet:ip-address. I suggest to remove the reference statement.

2021-05-14 08:35 UTC, sbarguil commented on yang/ietf-l3vpn-ntw.yang
> +                          "Virtual IPv4 addresses for a single VRRP group";
```suggestion
                          "Virtual addresses for a single VRRP group";
```

2021-05-14 08:35 UTC, sbarguil commented on yang/ietf-l3vpn-ntw.yang
> +                      leaf virtual-ip-address {
```suggestion
                      leaf-list virtual-ip-address {
```

2021-05-18 08:57 UTC, boucadair commented on yang/ietf-l3vpn-ntw.yang
> +                          "Virtual addresses for a single VRRP group";
```suggestion
                          "Virtual IP addresses for a single VRRP group. ";
```

2021-05-18 08:57 UTC, boucadair commented on yang/ietf-l3vpn-ntw.yang
> +                          Version 3 for IPv4 and IPv6.  Section 1.2";
```suggestion
                          Version 3 for IPv4 and IPv6,  Sections 1.2 and 1.3";
```

2021-05-18 08:58 UTC, merged